[manifest]
version = "0.0.1"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local discard_button = {n=G.UIT.C, config={id = 'discard_button',align = \"tm\", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.RED, button = \"discard_cards_from_highlighted\", one_press = true, shadow = true, func = 'can_discard'}, nodes={"
position = "before"
payload = '''
local store_button = {n=G.UIT.C, config={id = 'store_button',align = "tm", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.GOLD, button = "discard_cards_from_highlighted", one_press = true, shadow = true, func = 'can_discard'}, nodes={
    {n=G.UIT.R, config={align = "cm", padding = 0}, nodes={
        {n=G.UIT.T, config={text = "Hold", scale = text_scale, colour = G.C.UI.TEXT_LIGHT, focus_args = {button = 'z', orientation = 'bm'}, func = 'set_button_pip'}}
    }}
}}
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "G.SETTINGS.play_button_pos == 1 and play_button or discard_button,"
position = "after"
payload = '''
hold_button
'''
match_indent = true
times = 1